package Visao;

import DAO.SistemaDAO;
import Modelo.BeanSistema;
import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Personaliza extends javax.swing.JDialog {
    
    BeanSistema sistema = new BeanSistema();
    SistemaDAO sistemaDao = new SistemaDAO();
    Principal principal = new Principal();
    Login login = new Login();
    
    boolean mudanca = false;
    
    public Personaliza(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if(sistemaDao.corSistema() == Color.BLACK){
           radio_preto.setSelected(true);
        }
        else if(sistemaDao.corSistema() == Color.BLUE){
            radio_azul.setSelected(true);
        }
        else{
            radio_padrao.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_mudar_nome = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        radio_preto = new javax.swing.JRadioButton();
        radio_padrao = new javax.swing.JRadioButton();
        radio_azul = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btn_imagem1 = new javax.swing.JButton();
        btn_imagem2 = new javax.swing.JButton();
        btn_imagem3 = new javax.swing.JButton();
        slide = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(795, 125));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("(Cor)");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Alterar nome da escola");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_mudar_nome.setEditable(false);
        txt_mudar_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt_mudar_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mudar_nomeFocusGained(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Guardar Alterações");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        radio_preto.setForeground(new java.awt.Color(0, 51, 51));
        radio_preto.setText("Preta");
        radio_preto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_pretoItemStateChanged(evt);
            }
        });
        radio_preto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pretoActionPerformed(evt);
            }
        });

        radio_padrao.setForeground(new java.awt.Color(0, 51, 51));
        radio_padrao.setText("Padrão");
        radio_padrao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_padraoItemStateChanged(evt);
            }
        });

        radio_azul.setForeground(new java.awt.Color(0, 51, 51));
        radio_azul.setText("Azul");
        radio_azul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_azulItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Alterar Imagem");

        btn_imagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/sala-de-aula-miniatura.jpg"))); // NOI18N
        btn_imagem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 137, 233), 4, true));
        btn_imagem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_imagem1MouseEntered(evt);
            }
        });
        btn_imagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imagem1ActionPerformed(evt);
            }
        });

        btn_imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/sala-de-aula1-miniatura.jpg"))); // NOI18N
        btn_imagem2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 137, 233), 4, true));
        btn_imagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imagem2ActionPerformed(evt);
            }
        });

        btn_imagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/sala-de-aula2-miniatura.jpg"))); // NOI18N
        btn_imagem3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(94, 137, 233), 4, true));
        btn_imagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imagem3ActionPerformed(evt);
            }
        });

        slide.setOrientation(javax.swing.JSlider.VERTICAL);
        slide.setValue(100);
        slide.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_mudar_nome)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_imagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_padrao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_preto)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio_azul))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_imagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_imagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mudar_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(radio_padrao)
                                    .addComponent(radio_preto)
                                    .addComponent(radio_azul))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_imagem2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btn_imagem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_imagem3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_mudar_nome.setEditable(true);
        txt_mudar_nome.setText(sistemaDao.nomeSistema());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        
        if(!txt_mudar_nome.getText().isBlank()){
            sistema.setNomeEscola(txt_mudar_nome.getText());
            sistemaDao.alterarNome(sistema);
            principal.nome_escola.setText(txt_mudar_nome.getText());
        }
        
        if(radio_preto.isSelected()){
            sistema.setCor("preto");
        }
        else if(radio_azul.isSelected()){
            sistema.setCor("azul");
        }
        else if(radio_padrao.isSelected()){
            sistema.setCor("padrao");
        }
        if(mudanca){
            
            sistemaDao.alterarCor(sistema);
            principal.painel_frontal_cima.setBackground(sistemaDao.corSistema());
            principal.painel_frontal_baixo.setBackground(sistemaDao.corSistema());
            
            JOptionPane.showMessageDialog(null, "Alterações guardadas. O sistema tem que ser reiniciado"
                    + " para veres as alterações!");
            this.dispose();
            System.exit(0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Não houve nenhuma alteração!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_imagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imagem1ActionPerformed
        // TODO add your handling code here:
        slide.setValue(100);
    }//GEN-LAST:event_btn_imagem1ActionPerformed

    private void btn_imagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imagem2ActionPerformed
        // TODO add your handling code here:
        slide.setValue(50);
    }//GEN-LAST:event_btn_imagem2ActionPerformed

    private void btn_imagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imagem3ActionPerformed
        // TODO add your handling code here:
        slide.setValue(0);
    }//GEN-LAST:event_btn_imagem3ActionPerformed

    private void radio_padraoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_padraoItemStateChanged
        // TODO add your handling code here:
        if(radio_padrao.isSelected() ){
            radio_preto.setSelected(false);
            radio_azul.setSelected(false);
            mudanca = true;
        }
        else if(!radio_preto.isSelected() && !radio_azul.isSelected()){
            radio_padrao.setSelected(true);
        }
    }//GEN-LAST:event_radio_padraoItemStateChanged

    private void radio_pretoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_pretoItemStateChanged
        // TODO add your handling code here:
        if(radio_preto.isSelected()){
            radio_padrao.setSelected(false);
            radio_azul.setSelected(false);
            mudanca = true;
        }
        else if(!radio_padrao.isSelected() && !radio_azul.isSelected()){
            radio_preto.setSelected(true);
        }
    }//GEN-LAST:event_radio_pretoItemStateChanged

    private void radio_azulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_azulItemStateChanged
        // TODO add your handling code here:
        if(radio_azul.isSelected()){
            radio_preto.setSelected(false);
            radio_padrao.setSelected(false);
            mudanca = true;
        }
        else if(!radio_padrao.isSelected() && !radio_preto.isSelected()){
            radio_azul.setSelected(true);
        }
    }//GEN-LAST:event_radio_azulItemStateChanged

    private void radio_pretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pretoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_pretoActionPerformed

    private void txt_mudar_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mudar_nomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mudar_nomeFocusGained

    private void btn_imagem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imagem1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imagem1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Personaliza dialog = new Personaliza(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imagem1;
    private javax.swing.JButton btn_imagem2;
    private javax.swing.JButton btn_imagem3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radio_azul;
    private javax.swing.JRadioButton radio_padrao;
    private javax.swing.JRadioButton radio_preto;
    private javax.swing.JSlider slide;
    private javax.swing.JTextField txt_mudar_nome;
    // End of variables declaration//GEN-END:variables
}
