package Visao;

import DAO.ProfessorDAO;
import Modelo.BDados;
import Modelo.BeanProfessor;
import Modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author promessa
 */
public class TabelaListarProfessor extends javax.swing.JFrame {

    BDados banco = new BDados();
    BeanProfessor professor = new BeanProfessor();
    ProfessorDAO professorDao = new ProfessorDAO();
    
    private int classeAuxiliar;
    
    public TabelaListarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_codEditarProfessor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_editarProfessor = new javax.swing.JButton();
        txt_editarNomeProfessor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_editarClasseProfessor = new javax.swing.JTextField();
        btn_guardarProfessor = new javax.swing.JButton();
        btn_atulizarProfessor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_editarSalarioProfessor = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cod");

        btn_editarProfessor.setText("Editar");
        btn_editarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarProfessorActionPerformed(evt);
            }
        });

        txt_editarNomeProfessor.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Classe");

        txt_editarClasseProfessor.setEnabled(false);
        txt_editarClasseProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editarClasseProfessorActionPerformed(evt);
            }
        });

        btn_guardarProfessor.setText("Guardar");
        btn_guardarProfessor.setEnabled(false);
        btn_guardarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarProfessorActionPerformed(evt);
            }
        });

        btn_atulizarProfessor.setBackground(new java.awt.Color(51, 51, 51));
        btn_atulizarProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btn_atulizarProfessor.setText("Atualizar");
        btn_atulizarProfessor.setEnabled(false);
        btn_atulizarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atulizarProfessorActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Salário");

        txt_editarSalarioProfessor.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_guardarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codEditarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_editarSalarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_atulizarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_editarNomeProfessor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_editarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_editarClasseProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_editarClasseProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_editarProfessor)
                            .addComponent(jButton2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_editarNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_atulizarProfessor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codEditarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_guardarProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_editarSalarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_editarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarProfessorActionPerformed
        // TODO add your handling code here:
        try{
            professor.setBI(Integer.parseInt(txt_codEditarProfessor.getText()));
            ArrayList pesquisaProfessor = professorDao.pesquisar(professor);
            
            if(txt_codEditarProfessor.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Inserir código do professor!");
            }
            else if(!txt_codEditarProfessor.getText().isEmpty() && pesquisaProfessor.size() != 0){
                /* Activando os campos desativados */
                btn_guardarProfessor.setEnabled(true);
                txt_editarClasseProfessor.setEnabled(true);
                txt_editarNomeProfessor.setEnabled(true);
                txt_editarSalarioProfessor.setEnabled(true);
                txt_editarNomeProfessor.setText(String.valueOf(pesquisaProfessor.get(1)));
                txt_editarSalarioProfessor.setText(String.valueOf(pesquisaProfessor.get(2)));
                txt_editarClasseProfessor.setText(String.valueOf(pesquisaProfessor.get(4)));
            }
            else{
                JOptionPane.showMessageDialog(null, "Professor não Encontrado!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Digite valor numérico", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btn_editarProfessorActionPerformed

    private void btn_guardarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarProfessorActionPerformed
        
        professor.setNome(txt_editarNomeProfessor.getText());
        professor.setClasse(Integer.parseInt(txt_editarClasseProfessor.getText()));
        professor.setBI(Integer.parseInt(txt_codEditarProfessor.getText()));
        professor.setSalario(Double.parseDouble(txt_editarSalarioProfessor.getText()));
        professorDao.editarProfessor(professor);
        btn_atulizarProfessor.setEnabled(true);
        
    }//GEN-LAST:event_btn_guardarProfessorActionPerformed

    private void btn_atulizarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atulizarProfessorActionPerformed
        // TODO add your handling code here:
        
        if(professor.getClasse() == 0){
            carregaTabela(classeAuxiliar);
        }
        else{
            professor.setClasse(Integer.parseInt(txt_editarClasseProfessor.getText()));
            carregaTabela(professor.getClasse());
        }
    }//GEN-LAST:event_btn_atulizarProfessorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            if(!txt_codEditarProfessor.getText().isEmpty()){
                btn_atulizarProfessor.setEnabled(true);
                professor.setBI(Integer.parseInt(txt_codEditarProfessor.getText()));
                ArrayList pesquisaProfessor = professorDao.pesquisar(professor);
                classeAuxiliar = (int)pesquisaProfessor.get(4);
                professorDao.eliminar(professor);
            }
            else{
                JOptionPane.showMessageDialog(null, "Entre com o código do professor!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao eliminar!" + e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_editarClasseProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editarClasseProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editarClasseProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaListarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaListarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaListarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaListarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaListarProfessor().setVisible(true);
            }
        });
    }
    public void carregaTabela(int cod) {
        
        String colunas[] = {"Num", "Nome", "Classe"};
        ArrayList dados = new ArrayList();
        banco.ligar();
        
       String addSQL = "select id_professor, professor.nome, classe from professor where classe = ?";
        try{
            banco.ps = banco.con.prepareStatement(addSQL);
            banco.ps.setInt(1, cod);
            banco.rs = banco.ps.executeQuery();
            while(banco.rs.next()){
                dados.add(new Object[]{banco.rs.getInt(1), banco.rs.getString(2), banco.rs.getString(3)});
            }
        }catch(SQLException e){
            System.out.println("Erro ao adicionar no banco");
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTable1.setModel(modelo);
        
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(85);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(260);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(85);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atulizarProfessor;
    private javax.swing.JButton btn_editarProfessor;
    private javax.swing.JButton btn_guardarProfessor;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_codEditarProfessor;
    private javax.swing.JTextField txt_editarClasseProfessor;
    private javax.swing.JTextField txt_editarNomeProfessor;
    private javax.swing.JTextField txt_editarSalarioProfessor;
    // End of variables declaration//GEN-END:variables
}
